### ISSUE TITLE
LastFM scrobbling doesn't work?

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#105]
Is setting `api_key` and `secret` enough to get LastFM scrobbling working? I'm not able to get my stats updated on my lastfm profile.

**Comment by sprnza** [comment]
Aha! I've found a "Link" button at my account settings. When I press the button I get this error:

```
Invalid API key. If you are a third party developer see our authentication how-to to find out more.
```

The key is valid

**Comment by sprnza** [comment]
Actually I don't understand how it will work if I add my api_key and secret for system service. How it will distinguish what users to scrobble to?

**Comment by spl0k** [comment]
To get scrobbling to work, you have to:
- get an API key and shared secret from LastFM and add those to supysonic's configuration
- link your supysonic user to your LastFM profile by visiting your profile in supysonic's web UI
- tell your client you want to scrobble (some don't do it automatically)

When getting your keys from LastFM, you don't need to provide a callback URL or an application homepage.
There was an issue when trying to link an account, this is now fixed.
When you allow the application on LastFM, it seems to ignore whether supysonic is served over HTTP or HTTPS and redirect you to an HTTPS URI. If your supysonic instance isn't on HTTPS you'll have to manually change the URL LastFM is redirecting you to.

As for your last question: the keys you are getting from LastFM and putting in the configuration are only used to identify an application, not users. Each supysonic user can be linked to any LastFM user. By clicking the _Link_ button in their supysonic profile, users are redirected to LastFM which ask them to log in and allow supysonic to act on their behalf. This generates a token which is then used to identify the user.

**Comment by sprnza** [comment]
I've migrated to docker and I don't have the issue anymore. As soon as it seems to me that I had an extremely broken set up I close this.
