### ISSUE TITLE
Recently Played support

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#107]
Hi there!
I failed to locate a recently played functionality in the subsonic api, but both jumstash and dsub have these auto albums in them. Is it supposed to be supported by supysonic? Seems like it doesn't work for me.

**Comment by spl0k** [comment]
Recently played albums are returned by `getAlbumList` (when using folder-based browsing) or `getAlbumList2` (when using tags). Both are supported by supysonic.
Which client are you using and what happens when you try to get these albums?

**Comment by sprnza** [comment]
I use jamstash and Ultrasonic. I do get some list of recently played albums but it doesn't get updated.

**Comment by spl0k** [comment]
I suppose you're using PostgreSQL, I noticed the behaviour you're experiencing when using this DBMS.
It will be fixed soon.
