### ISSUE TITLE
Error when Scanning

### ISSUE THREAD

**Issue by zhdenny** [spl0k/supysonic#108]
I receive this error (screenshot link) when performing any Scan. Please help.

https://i.imgur.com/xgatvW5.png

**Comment by zhdenny** [comment]
The folder I gave it DOES have non-audio files in it........would that be the problem? It seems to be demanding "Attribute Track.title"

I went ahead and fed it a different folder....one which only has Audio-Related files in it (MP3, FLAC, jpg, etc)......and that scanned much much further (18,000+ files scanned) but eventually resulted in same error. What is going on?

**Comment by spl0k** [comment]
Non audio files shouldn't be a problem. The issue you're seeing is because at least one audio file is missing some metadata (such as a title), but this should be fixed since 918cd11262a15c581d9ea88bb399955e912fe940.
I can tell from your stack trace that your supysonic installation isn't up-to-date with _master_. Please pull the latest changes, update your installation (by running `python setup.py install`) and try again.

**Comment by zhdenny** [comment]
@spl0k 
Sorry to bother you again......but I hit the same scanning error. I am now trying to do as you recommend....updating to the latest....so I am attempting to do that from bashing inside the docker container.

I cloned the latest from your github and ran `python setup.py install`

After that, I tried `supysonic-cli folder list` and get the following error message. Basically, every supysonic-cli command results in error now.

https://i.imgur.com/I5aLFLr.png

How do I go about updating the Docker Container to the latest version......Looking at the Dockerfile for it, I would have thought it would be grabbing the latest version from your github. But it seems to be grabbing some version from May 2018
https://hub.docker.com/r/foosinn/supysonic/~/dockerfile/

**Comment by spl0k** [comment]
Glad to hear your issues are solved.
About version numbers, supysonic doesn't define any coherent version number. There's a _0.3_ defined somewhere but that never gets updated. The only reliable information you can get is the git commit hash.
