### ISSUE TITLE
Virtualenv error with supysonic-cli

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#109]
Hi

I am trying to instal and run undervirtualenv. I did

virtualenv -p python2.7 supysonic
source bin/activate

then added the sources and did

pip install .
python setup.py install

The server works but I cant get the supysonic-cli to work , throws the error below

```
supysonic-cli
Traceback (most recent call last):
  File "/media/DRIVE/opt/supysonic/bin/supysonic-cli", line 4, in <module>
    __import__('pkg_resources').run_script('supysonic==0.3', 'supysonic-cli')
  File "/media/DRIVE/opt/supysonic/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/media/DRIVE/opt/supysonic/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/supysonic-cli' not found in metadata at '/media/DRIVE/opt/supysonic/lib/python2.7/site-packages/supysonic-0.3.dist-info'

```

**Comment by spl0k** [comment]
Hi,

The documentation (and perhaps what I told on other issues) is misleading. You should either use `pip` or `setup.py` to install the project, but not both. Using both methods will lead to the error you're getting.
Also, for some reason, the `pip` method doesn't seem to work with python2.

To fix your issue, you'll have to recreate your virtual environment and install supysonic by only using the `python setup.py install` command.

Thanks for noticing, the documentation will be updated soon.
