### ISSUE TITLE
wav support?

### ISSUE THREAD

**Issue by zhdenny** [spl0k/supysonic#110]
Noticed wav files are overlooked. Any chance these get supported?

**Comment by spl0k** [comment]
Only files that _mutagen_ can read are added to the library. That means _ASF, FLAC, MP4, Monkey’s Audio, MP3, Musepack, Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files_ (as per [mutagen's documentation](https://mutagen.readthedocs.io/en/latest/)).
RIFF/WAVE support for mutagen is currently in the works (quodlibet/mutagen#207, quodlibet/mutagen#321). Until this is done, supysonic will continue to ignore wav files.

**Comment by spl0k** [comment]
_mutagen_ now supports WAV files. If you update it to version 1.45.0 or later Supysonic should be able to pick up WAV files.
