### ISSUE TITLE
Use Pony migrations

### ISSUE THREAD

**Issue by hhm0** [spl0k/supysonic#112]
First of all, thank you so much, @spl0k, for the wonderful project!

Pony is implementing migrations (see <a href="https://www.github.com/ponyorm/pony/issues/16#issuecomment-400161683">here</a>). Perhaps the existing migations can be migrated (pun intended :-) ) to use the Pony migration system.

This way, migrations (and therefore Supysonic upgrades in general) can be automated. This would then enable easy upgrades with Supysonic Docker images, as follows: A startup script would check if the latest software (in case a newer Docker image had benn pulled since last run) has a newer schema than the existing database, and if so, the migrations can be applied in an easy manner via Pony. This would enable just pulling a new Docker image and restarting in order to upgrade Supysonic; it would also most likely make upgrades easier for Linux distro package managers.

See also #95.

Thanks again!

**Comment by spl0k** [comment]
Automating schema migration (and database setup in general) is something I considered even before #95 got opened. Supysonic's setup always required users (new and existing alike) to get their hands dirty, and that's something I'd like to change.
I'm not sure I'll use Pony's migration system though (at least for now), for the following reasons:
- migrations are still under development and aren't available in any published release. Even if Supysonic itself doesn't have a release strategy, I don't want to rely on dependencies that aren't deemed stable.
- recent Pony updates proven to be not so production ready (even if the authors reacted quickly), that made me a bit concerned about Pony as a whole.
- the documentation is almost inexistent and can be resumed to "_here's how you can create a migration, to apply it use this, now fiddle with it_", no docs on the migration API.
- it seems to only apply to schema migration, data migration feels a bit overlooked.
- Supysonic uses a few schema definitions that currently can't be expressed with Pony's API.

**Comment by spl0k** [comment]
Custom migration system added. See comment on #95.

**Comment by hhm0** [comment]
Hi,

I'm late in responding; I apologize :-).

I probably should have titled this issue "support automatic
migrations", since it made no difference to me whether Pony's
migration system was used or not. :-)

And now I see that you implemented automatic migrations! Thank you so,
so much! :-)
