### ISSUE TITLE
Feature Request: Internet Radio

### ISSUE THREAD

**Issue by MDCEY** [spl0k/supysonic#114]
Any chance we can get internet radio added to supysonic?

![image](https://user-images.githubusercontent.com/3812864/45217469-144c7f00-b29c-11e8-97be-28a2c1addc36.png)

:edit:
Just noticed it's on the 'Not decided list, in your docs'. I guess we can just consider this a +1 for the feature

**Comment by gsantner** [comment]
subscribed.

would be very cool addition

**Comment by gsantner** [comment]
Just leaving this here:

<https://www.madsonic.org/pages/inc/api/examples/internetRadioStations_example_1.xml>

```
<madsonic-response xmlns="http://madsonic.org/restapi" status="ok" version="2.0.0" type="madsonic">
<internetRadioStations>
<internetRadioStation id="0" name="NRK P1" streamUrl="http://lyd.nrk.no/nrk_radio_p1_ostlandssendingen_mp3_m" homePageUrl="http://www.nrk.no/p1"/>
<internetRadioStation id="1" name="NRK P2" streamUrl="http://lyd.nrk.no/nrk_radio_p2_mp3_m" homePageUrl="http://p3.no"/>
</internetRadioStations>
</madsonic-response>
```

Nearly some but on url `https://example.com/supysonic/rest/getInternetRadioStations.view?u=xxxx&p=xxxx&c=xxxx` and subsonic instead of [madsonic](https://www.madsonic.org/pages/apiV2.jsp#getInternetRadioStations).

**Comment by thecarlhall** [comment]
@spl0k I've started working on this locally. I have the initial code shaped out, but need to write tests. I'd like to contribute and more to the api.

**Comment by spl0k** [comment]
👍 feel free to file a PR when you think it's ready.

**Comment by thecarlhall** [comment]
Posted a PR for this. All feedback is greatly appreciated. 
https://github.com/spl0k/supysonic/pull/187

**Comment by spl0k** [comment]
Closing this, as #187 have been merged.
