### ISSUE TITLE
Download doesn't work?

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#131]
Hi there!
If I try to download an album using Jamstash I get an error: 

```
{
  "subsonic-response": {
    "error": {
      "code": 10, 
      "message": "Missing callback"
    }, 
    "status": "failed", 
    "version": "1.8.0"
  }
}
```

Isn't it implemented yet?

**Comment by spl0k** [comment]
I don't know what Jamstash is trying to achieve here. According to the API docs, the [download method](http://www.subsonic.org/pages/api.jsp#download) should only be used to download single media files, not whole albums nor folders.
The method is implemented, but only for individual media files.

**Comment by sprnza** [comment]
Hi @spl0k ! Thanks for the reply. Since it seems like Jamstash is not maintained any more I ask here if I may. 

Do you have "download" button in an album view?
![download](https://camo.githubusercontent.com/fb175b8bd08cd3e1e27947aed6c6f9374cc9d89d/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363434343333382f323132303634322f37653936326233612d393162652d313165332d383632382d6633333733376165306336382e6a7067)

 I've seen in the issues of Jamstash that they've fixed a bug that prevent hiding download buttons when download is disabled long ago. So my though is "Is download functionality enabled properly in supysonic?" I am able to download tracks using Subsonic but it seems like Jamstash doesn't "see" download enabled for my account. I haven't found any way to disable or enable download in supysonic settings btw.

**Comment by spl0k** [comment]
I see the download button on folder/album list
![image](https://user-images.githubusercontent.com/2974943/48279808-f80ebf00-e451-11e8-9c2d-11138e548f06.png)

but not in the track list
![image](https://user-images.githubusercontent.com/2974943/48279856-22f91300-e452-11e8-8644-d8bd594e87cc.png)

Supysonic doesn't support the fine grained permissions Subsonic has, so you got nothing to set. When asked, Supysonic answer any user can use the download feature.

**Comment by spl0k** [comment]
You should now be able to download individual tracks, but also albums and folders in which case they are sent in a `zip` archive (to be nice to Windows users that aren't used to see tarballs).
I haven't checked how Subsonic handles this but when downloading a folder you'll only get the tracks (and only tracks) from the topmost level (this isn't recursive).

I'll keep this issue open as it can still be improved (adding covers, preventing naming collisions with albums spread across several folders, preventing empty archives...)

**Comment by sprnza** [comment]
Yay! Works like a bomb via Jamstash!

**Comment by pR0Ps** [comment]
Since #223 has been merged I believe this can be closed

**Comment by spl0k** [comment]
Well I guess the naming-collision issue (which I actually never tried to see if it effectively exists) is still there but yeah I think #223 covers all the download use cases we can think of 👍

**Comment by pR0Ps** [comment]
Even if names collide, all the files will still be added to the zip file. When the zip file is extracted most programs will ask what you want to do about the collision (rename, ignore, etc).

Not an optimal user experience, but should at least be functional :)
