### ISSUE TITLE
Gateway timeouts when calling getAlbumList2

### ISSUE THREAD

**Issue by mremallin** [spl0k/supysonic#140]
Versions:
supysonic - Commit c0d9d616c88a39f47401a4a2bea9bf41827a5733
python - 3.7.2
sqlite3 - 3.27.2
pony - 0.7.9

Library stats:
Artists - ~2000
Albums - ~2000
Tracks - ~20000

Issues:
I'm seeing slow responses to the following REST request, which is causing Apache timeouts. Running in debug mode with just flask, I'm seeing a response time of ~140s:

rest/getAlbumList2.view?v=1.8.0&c=Clementine&u=<my_user>&p=enc:<my_pass>&type=alphabeticalByName&size=500&offset=0

Workaround:
Comment out both track_with_cover lines which select on the track/folder tables within as_subsonic_album of the Album class.
This drops the response time of the above query from 140s to 8.2s

**Comment by spl0k** [comment]
That's some pretty high response times you're getting there, even with your workaround. I'm getting around 11 seconds with a similar-sized library.

The queries behind the lines you commented aren't complex, they're basically a `SELECT FROM WHERE` with an extra `JOIN` on the first one. I suspect some missing indexes.
Is your database on SQLite?

**Comment by spl0k** [comment]
I added indexes on all foreign keys. The response time for the `getAlbumList2.view?size=500` request dropped from 11s to 3.8s in my case.
Please let me know if you still have issues.

**Comment by mremallin** [comment]
Thank you for the update! Correct, I am using SQLite. Your commit dropped all of my requests to the order of 6-8s per 500 albums and I'm no longer seeing timeouts.
