### ISSUE TITLE
Watcher doesn't work for several folders

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#142]
Hi there!
I've added another folder into my medialibrary and seems like watcher doesn't pick it up properly. It looks like it completely ignoring it. Is it a case or misconfiguration on my side?

**Comment by spl0k** [comment]
You have to restart the watcher when you add or delete a folder as there is currently no way to notify the watcher such thing happened. That's the last point of #77.

**Comment by sprnza** [comment]
Yep, I saw the checklist. I run supysonic inside docker container, and I've restarted the container several times, but watcher still doesn't see the new folder for some reason.

**Comment by sprnza** [comment]
Just tried another time and it works. Sorry for bothering
