### ISSUE TITLE
MySQL connection

### ISSUE THREAD

**Issue by DOFfactory** [spl0k/supysonic#152]
I am running supysonic in a docker with bridge mode. I cannot make a connection between supysonic and my MySQL on host (not in docker!), despite following all the manuals. I am able to connect to MySQL from other dockers through `mysql://host.docker.internal` ¦ `3306`. It always falls back to the internal default SQLite.

I haven't tried yet running supysonic docker in host mode, but this is not preferred.

**Comment by spl0k** [comment]
Supysonic will throw an error if it can't connect to the database that is set in the configuration file, it will never fall back to SQLite. Check your configuration file if doesn't have several `database_uri` entries. Or maybe the docker container you're using is rewriting the configuration file?

**Comment by DOFfactory** [comment]
Hm, none of these I am afraid. It always created a `supysonic.db` file in the folder where the settings were stored. I made sure that all the other lines are commented out in the config file.

**Comment by spl0k** [comment]
Well I don't have experience with Docker, but if you'd tell me which container you're using and how you set it up I will take a look as to why this is happening.
This SQLite file really shouldn't be created if the config points to a MySQL database.

**Comment by DOFfactory** [comment]
I am using this docker image: https://github.com/ultimate-pms/docker-supysonic

All builds well, but I crash and burn in linking my host MySQL with this. The supysonic.db is always SQLite3. Other places (https://github.com/glogiotatidis/supysonic-docker) use mysql.sql from a 'schema' folder, but this docker has none of these. Could you help?

**Comment by sentriz** [comment]
@DOFfactory are you using that image's SUPYSONIC_DB_URI env var, or have you mounted [this config](https://github.com/ultimate-pms/docker-supysonic/blob/master/docker-compose.yml#L12) with something like
```
[base]
database_uri = mysql://...
```

**Comment by DOFfactory** [comment]
Hi @sentriz I changed both to my mysql:// path, as suggested here: https://stackoverflow.com/a/49907758

**Comment by sentriz** [comment]
@DOFfactory are you using [this](https://github.com/ultimate-pms/docker-supysonic/blob/master/docker-compose.yml) default compose file or similar?

also try get a shell in a container and try to see if you can reach your host's mysql instance. eg.
`$ sudo docker run -it python:3-alpine3.7 nc host.docker.internal 3306` (the supy image is based on python:3-alpine3.7, so it should be similar enough)

if you get `bad address 'host.docker.internal'` try your host's default interface's local address (check `ifconfig` or something)

mine would be 
`$ sudo docker run -it python:3-alpine3.7 nc 192.168.1.1 3306`

**Comment by DOFfactory** [comment]
hm, tried to change, but unfortunately due to a rather strange docker behaviour I have to start from scratch. Would it be possible to provide an easy to setup and maintained docker container? What is available at the moment is pretty substandard and needs a lot of tweaking.

**Comment by sentriz** [comment]
Hmm I have used that image in the past without a problem. What sort of strange behaviour are you getting?

**Comment by spl0k** [comment]
The configuration, which is copied from [the sample](https://github.com/spl0k/supysonic/blob/master/config.sample), is stored in the docker image as `/var/lib/supysonic/.supysonic`. If I understand things right this `/var/lib/supysonic` folder is mapped from a `config` folder from the host.
This file is then [rewritten with values taken from the environment](https://github.com/ultimate-pms/docker-supysonic/blob/master/docker/dockerconfig.py). The variable that could be bothering us here is `SUPYSONIC_DB_URI`. This environment variable isn't defined in the [docker-compose.yml](https://github.com/ultimate-pms/docker-supysonic/blob/master/docker-compose.yml) but we can see it being set in the [Dockerfile](https://github.com/ultimate-pms/docker-supysonic/blob/master/Dockerfile). So depending on your configuration I suggest you take a look at both those files.

As for the SQL files you mention, they are [provided with Supysonic](https://github.com/spl0k/supysonic/tree/master/supysonic/schema) and the repository is cloned by the Dockerfile.

And thank you @sentriz for trying to help.

**Comment by spl0k** [comment]
@DOFfactory did you sort it out?

**Comment by DOFfactory** [comment]
Hi @spl0k, no, I changed server software. Easier installation, and more detailed setup guide is needed.
