### ISSUE TITLE
Transcoding help

### ISSUE THREAD

**Issue by DOFfactory** [spl0k/supysonic#153]
Hi, I am migrating from *sonic to supysonic. Everything seems to work, except the desired transcoding. MP3 is fine, and I try to consult the [wiki](https://github.com/spl0k/supysonic/wiki/Transcoding), but I cannot make it working. I tried to adjust the audio > opus transcoding originally used in [airsonic](https://www.reddit.com/r/airsonic/comments/8hyxf9/does_airsonic_support_opus/) (`ffmpeg -i %srcpath -map 0:0 -b:a %outrate -codec:a libopus -vbr on -f ogg -`). However, I have no luck, and the wiki is not helpful enough.  FFmpeg is in place and it should work, but it does not.

Could you please advise? Maybe use this opportunity to describe the wiki a bit more in detail too?

**Comment by spl0k** [comment]
Hi. Even if there wasn't any notable difference for this page, the wiki is outdated and you should be reading the files from the ["docs" folder](https://github.com/spl0k/supysonic/tree/master/docs) instead.
What does your transcoding configuration look like?
The Subsonic API regarding transcoding is a bit weird, you actually have to navigate to your profile page in Supysonic's web UI and set either a destination format or bitrate (or both) for the client you want to use for this client to be able to pick up transcoding.

I think your command is missing a `k` right after `%outrate` for FFmpeg to treat the value as kbps and not bps. So the command should be
```
ffmpeg -i %srcpath -map 0:0 -b:a %outratek -codec:a libopus -vbr on -f ogg -
```
This is coherent with the `%bk` that can be seen [here](https://www.reddit.com/r/airsonic/comments/8hyxf9/does_airsonic_support_opus/e41rrs2/).

**Comment by spl0k** [comment]
Hi. Did the previous comment help or are you still having issues?
