### ISSUE TITLE
Please upload your GPG public key somewhere

### ISSUE THREAD

**Issue by baldurmen** [spl0k/supysonic#154]
Hi!

I'm currently working on packaging supysonic in Debian ([ponyorm has recently been packaged!](https://ftp-master.debian.org/new/ponyorm_0.7.9-1.html)) and I can't find the GPG public key you've used to sign the latest tag:

650DF1C980B31881BE0DE2D58CE0313646D16165

It seems it's not on the SKS pool :(

Could you please upload it somewhere so I can download it? Debian packages typically verify that the upstream releases are signed and I need your public key for that process.

**Comment by spl0k** [comment]
Sorry, that whole GPG stuff is kinda new to me.
Uploading the key is done with the `gpg2 --send-keys` command, right? I struggled a bit to get it to work (I was getting cryptic _No such file or directory_ errors) but the key should now be available on the SKS pool.

**Comment by baldurmen** [comment]
Thanks a lot! Yeah, GPG can be ... challenging. The UX is terrible :(

I would highly suggest you read this GPG best-practices primer: https://riseup.net/en/security/message-security/openpgp/best-practices

It's a tad outdated (thanks to gpg2) but most advices there are still relevant.

Cheers!
