### ISSUE TITLE
ffplay fails to play streams

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#159]
Hi there! I'm not sure if it's supysonic related issue but I actually don't know where to start to debug. If I start streaming using ffmpeg like so:
```
ffplay -i https://mysupysonic/rest/download.view\?u\=Useraname\&c\=ClientName\&f\=json\&v\=1.9.0\&p\=enc:key\&id\=d07a13db-88a6-4396-9d38-37fdd9382832\&format\=raw -showmode 0 -autoexit -hide_banner -x 500 -y 500 -loglevel debug -nodisp
```
I got the process interrupted in the middle of the stream with such output:
```
 248.73 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f
[mp3float @ 0x7f2490640f80] invalid new backstep -1
 248.76 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.79 M-A: -0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.82 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.85 M-A: -0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.88 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.91 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.94 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
248.97 M-A: -0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f 
249.01 M-A:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f
[AVIOContext @ 0x7f2490326b00] Statistics: 10025824 bytes read, 0 seeks
```
I just wanted to ask: is there any way supysonic controls streaming process? Or it's pure ffplay-related issue?

**Comment by sprnza** [comment]
mplayer interrupts playback with output
```
EOF code: 1  

Uninit audio filters...
[libaf] Removing filter dummy 
Uninit audio: mpg123
[AVIOContext @ 0x7ff78d50fc80]Statistics: 18585620 bytes read, 10 seeks
alsa-uninit: pcm closed
vo: x11 uninit called but X11 not initialized..

Exiting... (End of file)

```
It seems like supysonic doesn't feed the whole file for some reason.
Jamstash and Android clients play fine though.

**Comment by sprnza** [comment]
It happens every single time I play a song. Should I poll supysonic somehow to keep it streaming?

**Comment by spl0k** [comment]
The `download.view` (with `id` matching a track) and `stream.view` (with `format=raw`) endpoints send files as-is, without any processing. I tested with some of my mp3 files and had no problem.
Did you observe the same behaviour with other files?
Maybe the connection gets closed before `ffplay` got the chance to download the whole file. If supysonic is behind a reverse proxy check if its configuration would cause connections to close prematurely. I doubt that's a supysonic only issue.

**Comment by sprnza** [comment]
Hi! Thanks for the response! Have you tried to play mp3 longer than 240 seconds with your instance using ffplay? Mine keeps aborting connection near 240 seconds of playback. I've got supysonic running in docker behind a reverse proxy, but per you suggestion I checked and disabled proxy's timeout settings, so it shouldn't be a problem now. I just wonder maybe supysonic running in wsgi mode could have a setting somewhere to close Keep-Alive connections on some timeout?

**Comment by spl0k** [comment]
Ok I managed to reproduce the issue with an other environment (gunicorn + Apache).
Unfortunately I don't think this is something that could be solved from supysonic's side.

If you don't want to change your server's configuration there is another workaround: calling `ffplay` with the `-infbuf` flag. I was then able to listen to a 18-minutes track that would otherwise end prematurely around 80 seconds. But please note that this will cause `ffplay` to buffer the whole file, it might be problematic if you use it on huge files.

**Comment by sprnza** [comment]
Thanks! Works like a bomb!
