### ISSUE TITLE
Entries for every track in Recently added

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [spl0k/supysonic#182]
With Airsonic for example it only had one entry for the folder added in Recently added but with Supysonic there's multiples for each track. 

![Screenshot_20200322-202429](https://user-images.githubusercontent.com/26030872/77257230-a8621980-6c7b-11ea-9eb1-2fccbb0323a0.png)

**Comment by sprnza** [comment]
The bug has been introduced in recent updates. It used to work properly.
