### ISSUE TITLE
Error on scan library

### ISSUE THREAD

**Issue by Vctrsnts** [spl0k/supysonic#184]
Hi,

I have supysonic in docker in Raspberry ( raspbian ) and when scan my library with:

`docker exec -it supysonic supysonic-cli folder scan Library`

I watch this error message:
```
Couldn't connect to the daemon, scanning in foreground
Scanning 'Library': 5603 files scanned/usr/local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:781: UserWarning: Possibly corrupt EXIF data.  Expecting to read 30 bytes but only got 28. Skipping tag 37510
  warnings.warn(
/usr/local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:802: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))

Scanning done
Added: 3 artists, 91 albums, 1975 tracks
Deleted: 1 artists, 385 albums, 11113 tracks
```
Where is the problem??

Thanks

**Comment by spl0k** [comment]
Hello,

This isn't an error but a warning. It means you have at least one cover art file with some invalid data.
It's mostly harmless and won't prevent you from using supysonic.

I'll try to see if I can at least make this kind of message more explicit.

**Comment by Vctrsnts** [comment]
Yes,

Is correct that you say. The problem is a cover. Delete all my covers and now the warning is not visible.

Thanks for all
