### ISSUE TITLE
"Contacting server, please wait" in DSub when navigating the library

### ISSUE THREAD

**Issue by dbogdanov** [spl0k/supysonic#191]
I am using DSub to connect to Supysonic running as a standalone debug server. There is an annoying issue that I cannot browse Library tab in the app, getting the "Contacting server, please wait" -- "A network error occurred. Retrying 1 of 4"  and so forth. 

At the same time, the album list and search within Home tab of DSub work fine, and I can play music. 

Also, if this is relevant, I am getting these errors in the log: 
```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.15.4-py2.7.egg/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.15.4-py2.7.egg/werkzeug/serving.py", line 294, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.15.4-py2.7.egg/werkzeug/serving.py", line 275, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
```

**Comment by spl0k** [comment]
Hello.

It seems you are using Python 2 which has reached its End-of-Life with the beginning of 2020. Supysonic have dropped Python 2 support shortly after, make sure you're running it under a compatible Python 3 installation (starting from Python 3.5).
If it still fails after this please come back at me with any error you might see in the logs and details about your deployment (Python version, the web server used, if it's behind a reverse-proxy, etc.) so I can try to reproduce it.

Regards.

**Comment by dbogdanov** [comment]
Indeed, this was an issue. Thanks for your feedback!
