### ISSUE TITLE
ignored_articles is not sent with getIndexes and getArtists

### ISSUE THREAD

**Issue by sumnerevans** [spl0k/supysonic#194]
Hello, I'm the maintainer of [Sublime Music](https://sublimemusic.app) and I have gotten a report of `ignored_articles` not being sent from Supysonic: https://gitlab.com/sublime-music/sublime-music/-/issues/264. I plan to create a fix for this on my end, but it would be nice if Subpysonic sent `ignored_articles` in both of those endpoints.

**Comment by spl0k** [comment]
Hello.

Supysonic target's Subsonic API version 1.9.0, this attribute was added with API version 1.10.0.
Changing the target API would require some work to be compliant/coherent. Plus this attribute would most likely be an empty value until we implement the feature behind it.

**Comment by baldurmen** [comment]
FWIW, this issue also affects me :)

I maintain `sublime-music` in Debian and it's a very nice client! It's a shame it doesn't work well with `supysonic`, as it would make a good music server-client combo.

Hopefully this can be solved before the [next Debian stable release](https://release.debian.org/bullseye/freeze_policy.html).
