### ISSUE TITLE
Support cover art for the m4a file format

### ISSUE THREAD

**Issue by PhilipVis** [spl0k/supysonic#196]
Would it be possible to add support to retrieve cover art information embedded to m4a files? 
M4a files don't support the ID3 tags used by other music file formats, but they use XMP instead. [This Stackoverflow answer](https://stackoverflow.com/a/44906491) has some information about it and the Mutagen library to use for m4a files.

**Comment by spl0k** [comment]
@baldurmen I'm considering using [MediaFile](https://github.com/beetbox/mediafile), a wrapper around mutagen which will be used by a future version of beets. I noticed it doesn't exist (yet) in Debian, would that be a problem wrt packaging?

**Comment by baldurmen** [comment]
@spl0k Thanks for the heads-up! I would have to package it, but:

* it doesn't have any crazy dependencies
* it has a testsuite
* it seems maintained

So no red flags for me. When you decide to use it, please ping me again and I'll start packaging it. Note it will delay me updating `supysonic` in Debian as new packages have to be manually reviewed by the FTP-masters team for copyright QA reasons.

**Comment by spl0k** [comment]
Would the freeze planning for _bullseye_ delay even more if we were to add the new dependency before the transition/soft freeze? (I'm not sure which one applies to `supysonic`)
I have to run (or write) some additional tests but the change is ready to be pushed.

**Comment by baldurmen** [comment]
You can't really push a new dependency to the archive during the soft-freeze if you don't have a very good reason for it. It's possible to do that during the transition, but I would be against packaging anything that isn't trivial or very well maintained, as if something needs to be corrected later it'll be a mess.

> I have to run (or write) some additional tests but the change is ready to be pushed.

Good to know! I'll start packaging mediafile then.

**Comment by baldurmen** [comment]
https://ftp-master.debian.org/new/python-mediafile_0.6.0-1.html

:)

**Comment by spl0k** [comment]
0183bcb69846471d2ba0c3ae7277e1a504e8b003 ;)
