### ISSUE TITLE
search 2 get folder ID for artist

### ISSUE THREAD

**Issue by vincentDcmps** [spl0k/supysonic#198]
hi not really an issue but I try to work on mopidy-subidy and I  notice that Id number return in artist result for search2 is the folder ID it is normal behavior?

**Comment by spl0k** [comment]
Yes, [`search`](http://www.subsonic.org/pages/api.jsp#search) and [`search2`](http://www.subsonic.org/pages/api.jsp#search2) allow to search the library using the folder hierarchy. What _artist_ and _album_ mean here depends on where the media files are stored and are to be considered from the media file level; for a give media file, its _album_ is the folder it's in and the _artist_ is this folder's parent.
Take this poorly drawn example:
```
Root
+-Folder
| +-Subfolder
| | +-Audio.ogg
| *-File.mp3
```
Here `Audio.ogg` has _artist_ `Folder` and _album_ `Subfolder`, but `Folder` is also the _album_ for `File.mp3`.
My guess is that Subsonic was first designed with the assumption that all users properly stored their media in a `Artist/Album/Track` file system structure.

If you want to search using the media files' metadata, where _artist_ and _album_ really match their meaning (as long as the files are properly tagged) you should use [`search3`](http://www.subsonic.org/pages/api.jsp#search3).

**Comment by vincentDcmps** [comment]
yes I have but search3 in the API call and it's work now thanks
