### ISSUE TITLE
FR: Support ignoredArticles in config

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#200]
Now the API points to 1.10.2 so is a good idea support set ignoredArticles in config file. 

Note: By default the value of ignoredArticles string is `The El La Los Las Le Les`.

**Comment by spl0k** [comment]
It was planned before you asked ;)

As the Subsonic API documentation is lacking, and I didn't want to deploy a Subsonic installation to test several scenarios, I implemented it in a way that was convenient (at least for me). This means that the articles are ignored only if they are separated from the rest of the name by a space, and it's done ignoring the case. When this would work in most of the cases, it would ignore some names where the separators aren't spaces. For example I have in my library the artist _THE→CHINA WIFE MOTORS_ still listed under _T_ when it could be under _C_ with some slight changes.

I considered adding some other articles to the default list, such as the Italian ones, but finally decided against it as some of them would have another meanings in other languages (_Il_ -> _He_ in French, or _I_)

**Comment by ogarcia** [comment]
> This means that the articles are ignored only if they are separated from the rest of the name by a space, and it's done ignoring the case.

I think that _this is the way_. As I can see in other sources. :-)
