### ISSUE TITLE
add support for endpoint without .view

### ISSUE THREAD

**Issue by vincentDcmps** [spl0k/supysonic#210]
@spl0k subsonic  call to endpoint without .view at the end works. what do you think to implement the support of these in supysonic?

**Comment by spl0k** [comment]
It could be nice to support it as well yes, especially since this extension disappeared from the API documentation. That means some newer clients could call the endpoints without the `.view`, making them incompatible with Supysonic.

**Comment by vincentDcmps** [comment]
OK I will take in charge this modification if you want

**Comment by spl0k** [comment]
Well go ahead then 👍

**Comment by vincentDcmps** [comment]
PR #211
