### ISSUE TITLE
Build man pages using sphinx

### ISSUE THREAD

**Issue by baldurmen** [spl0k/supysonic#225]
Hi,
Looking at the latest release (currently working on packaging 0.7.0 in Debian), I see you are now using sphinx to build the documentation.
This means we could now also build the man pages that way :)

Would you mind that? I'd be happy to send a PR to fix this and have all the docs+man pages built at the same time

**Comment by spl0k** [comment]
Hello 👋 

Having the man pages built and installed with the application is something I would love to have. There already was some work along that way (#215) but it lacked some required steps to actually be working.
Sphinx should already be configured to build them but I noticed it gives a different output than if they were built with `rst2man` (which you currently use to create the Debian package if I'm not mistaken). What's your plan regarding this? Are you going to keep the pages the way they are designed or do you need to modify them? (does Debian impose a specific layout?)

**Comment by baldurmen** [comment]
> Are you going to keep the pages the way they are designed or do you need to modify them?

I'll just rework the current man pages to be sphinx compliant. I have done that for other projects so it shouldn't be too hard.

>  (does Debian impose a specific layout?)

Nope, man pages are man pages, you could write them in raw roff if you wanted, but it's a PITA and using sphinx to translate RST to roff works better IMO :)
