### ISSUE TITLE
FR: Reach API level 1.11.0

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#235]
The new version [4.0.0](https://gitlab.com/ultrasonic/ultrasonic/-/releases/4.0.0) of [Ultrasonic](https://gitlab.com/ultrasonic/ultrasonic) will require a minimum API level of [1.11.0](http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.11.0.xsd) to be able to display the album list as it needs the musicFolderId parameter of the [getAlbumList](http://www.subsonic.org/pages/api.jsp#getAlbumList) endpoint. This change is due to the improvement of the offline mode, which now allows you to browse the downloaded collection as if you were online.

It would be interesting if Supysonic could reach this API level so that Ultrasonic users do not see their experience diminished at that point.

**Comment by spl0k** [comment]
Hello.
I'll take a look. Is this `musicFolderId` parameter the only 1.11.0 thing Ultrasonic needs or are there other features that are mandatory?

**Comment by ogarcia** [comment]
Yes, for now there is no other requirement than that.

**Comment by spl0k** [comment]
Hello again.
I've added the `musicFolderId` parameter on almost all endpoints that use it, and pushed the API version to 1.12.0. Don't hesitate to nudge me if you encounter any issue.

**Comment by ogarcia** [comment]
Sorry for the long delay, but I was away on vacation.

I just tested the latest changes and when I do the `ping.view` request instead of returning 1.12.0 it returns 1.10.2:
```
% curl 'https://server/rest/ping.view?u=user&c=Ultrasonic&f=json&p=enc:XXXXXX'
{"subsonic-response":{"status":"ok","version":"1.10.2"}}
```

Maybe the string needs to be changed here?
https://github.com/spl0k/supysonic/blob/master/supysonic/api/__init__.py#L8

**Comment by spl0k** [comment]
Indeed, my bad. It should now be fixed.

**Comment by ogarcia** [comment]
Ok. Now it works like a charm. Thanks!!!
