### ISSUE TITLE
Error during migration with 7.4

### ISSUE THREAD

**Issue by anayrat** [spl0k/supysonic#244]
Hello, I updated my supysonic from 7.2 to 7.4, but it seems this migration fails:

```
TypeError: 'pragmas' is an invalid keyword argument for this function
    with sqlite3.connect(file, **args) as conn:
  File "/home/supysonic/supysonic/lib/python3.7/site-packages/supysonic/schema/migration/sqlite/20230111.py", line 34, in apply
    m.apply(args.copy())
  File "/home/supysonic/supysonic/lib/python3.7/site-packages/supysonic/db.py", line 672, in init_database
    init_database(app.config["BASE"]["database_uri"])
```
Thanks for your help

**Comment by spl0k** [comment]
Hello. It should now be fixed if you update to the latest revision. There won't be a new release yet so you can get it either by cloning and installing from there, or by telling pip to install from the git repository:
```
pip install git+https://github.com/spl0k/supysonic.git
```

**Comment by anayrat** [comment]
Hello,
Thanks, I just added the line in the commit, and I was able to upgrade to 0.7.4

Thanks!
