### ISSUE TITLE
monitor music folder with inotify

### ISSUE THREAD

**Issue by andrenam** [spl0k/supysonic#25]
Just an idea for a new feature.
How about monitoring the music folders for changes using inotify? So that new files or updated files would be added instantly without re-scanning the whole library?

There is pyinotify that could be used for that.

I realize this feature would be Linux specific and wouldn't work on any other operating system. But it would really be a great improvement and I would guess most people run it on Linux. If not, it could be optional.

**Comment by spl0k** [comment]
I'll finally won't provide any *systemd* file and leave it to package maintainers. Yours might need a small update as it not a simple service anymore but a forking one.

I guess the daemon is stable enough (and merged to *master*) so I'll close this issue, even if I plan on improving it.
