### ISSUE TITLE
peewee.OperationalError: Server has gone away

### ISSUE THREAD

**Issue by Whisprin** [spl0k/supysonic#253]
Using MariaDB (mysql) as the database I'm encountering issues with the server after it has been running for several hours. For example after logging in with username and password on the webui the server
 throws this error: [supysonic.log](https://github.com/spl0k/supysonic/files/11239307/supysonic.log)

```
peewee.OperationalError: (2006, 'Server has gone away')
```

It seems to be related to the database server closing idle connections after 8h. And Supysonic or the database engine not reestablishing the connection.

The issue appears both with waitress and gunicorn.

**Comment by PeterRob** [comment]
Same problem here since the switch to peewee.

**Comment by spl0k** [comment]
I've pushed some fixes. It should now be ok for the web server and background scans. There might still be some issues with the watcher though.

**Comment by PeterRob** [comment]
Thanks, the updates seem to have fixed the error.
