### ISSUE TITLE
ValueError: badly formed hexadecimal UUID string in getAlbum.view

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#256]
When making a request to `getAlbum.view`, the Supysonic always gives `ValueError: badly formed hexadecimal UUID string` response (regardless of the id).

Sample request:
```curl
curl https://server.url.example/rest/getAlbum.view?id=1053&u=user&c=Ultrasonic&f=json&v=1.12.0&p=enc:encondedpass
```

Response:
```json
{"subsonic-response":{"error":{"code":0,"message":"ValueError: badly formed hexadecimal UUID string"},"status":"failed","version":"1.12.0"}}
```

Thinking it might be a problem with the database I recreated it from scratch but the problem persists.

Could there be something wrong with that endpoint?

**Comment by spl0k** [comment]
Except for folders all ids are UUIDs, you're passing an integer in your sample request. How are you retrieving it? My guess is you're mixing endpoints for tag-based browsing with data coming from folder-based endoints.

**Comment by ogarcia** [comment]
Right @spl0k , sorry for the noise, it [was our mistake](https://gitlab.com/ultrasonic/ultrasonic/-/merge_requests/1072).

That's what you said, we were using folder navigation but then asking for an album in tag navigation.
