### ISSUE TITLE
can't play songs with accented character when using supysonic wsgi

### ISSUE THREAD

**Issue by charmparticle** [spl0k/supysonic#259]
It took a bit of work to get supysonic wsgi working at all, but once I gave it permission to access my home folder (and copied my ~/.config/supysonic/supysonic.conf to /etc/supysonic), everything was hunky dory, except that I can't play music that has accented characters. It shows up in my player (dsub, sonixd, subtracks), but I can't play it or cache it.

Here's my apache config, which resides in /etc/apache2/conf-enabled/supysonic.conf:

```
WSGIScriptAlias /supysonic /var/www/supysonic/supysonic.wsgi
WSGIDaemonProcess /supysonic user=#1000 group=#1000
WSGIProcessGroup /supysonic
<Directory /var/www/supysonic>
   WSGIApplicationGroup %{GLOBAL}
   WSGIPassAuthorization On
   Require all granted
</Directory>
```

and here is the error I'm getting in my /var/log/apache2/error.log:

`mediafile.MutagenError: '': 'ascii' codec can't encode character '\\xe1' in position 112: ordinal not in range(128)`

my $LANG is en_US.UTF-8

my supysonic music database is mysql (mariadb) with the default utf8mb4 encoding

I don't experience this issue when I use the default python gunicorn server, but I want a "set it and forget it" solution; gunicorn poops out on me every now and again and I have to restart it, whereas apache2 does not.

**Comment by charmparticle** [comment]
solved it by finding a similar issue here. My fix was to emulate your solution to that issue, and update my /etc/apache2/envvars to comment out this line:

`export LANG=C`

and uncomment this line:

. /etc/default/locale

where /etc/default/locale has this:

`LANG=en_US.UTF-8`

Thanks, spl0k! supysonic is amazing.

**Comment by spl0k** [comment]
Hello. Thank you for the kind words, and I'm glad you managed to find a solution so quickly.
Just so I can understand, prior to your modification you were able to scan and browse your music but not play it? Are the accented characters only found in tags or do filenames also have some? Could you please paste the full stacktrace of the error?

Also could you please give some details on the problems you encountered with gunicorn?

**Comment by charmparticle** [comment]
Yeah, I could browse the music, but couldn't play it. The filenames themselves had accented characters.

How can I get a stack trace?

Regarding gunicorn, I used to open tmux and start supysonic in a tab, then disconnect. I would be able to use supysonic for maybe a day or two, and then I would inevitably have to open tmux, control-c the running supysonic process, and enter it again, because my subsonic clients would refuse to connect.
