### ISSUE TITLE
Provide systemd-friendly interface for watcher

### ISSUE THREAD

**Issue by tkiapril** [spl0k/supysonic#37]
While lots of linux distribution supported the classic init.d, systemd is becoming more and more popular among many distributions. Starting from jessie/15.04 builds of Debian and Ubuntu, systemd is fully supported, and even more systems are populated with systemd based daemon administration.

The thing is that systemd works the best with undaemonized processes where the main process won't fork but instead emit the output to stdout/stderr. It is difficult to utilize the current implementation to fit into a systemd service.

Thus, I suggest providing a simpler interface -- where `python watcher.py` or some simple script would persist with the terminal -- along with current one.

**Comment by spl0k** [comment]
62bcce331a318417c4bed6b81a1fba4d5d458497
