### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 88: ordinal not in range(128)

### ISSUE THREAD

**Issue by knealmarc** [spl0k/supysonic#43]
This is a solved problem, and it's really not a supysonic issue (ie webserver configuration) but I spent a bit of time hunting it down and thought it'd be useful to document.
##### TL;DR

The solution is already noted in the README.md - see the green in this [commit](https://github.com/spl0k/supysonic/commit/e523e01760f56e76793730d083520ca2bed76ccf?diff=unified)
### Details

Using the [DSub](https://f-droid.org/repository/browse/?fdid=github.daneren2005.dsub) android client, browsing to a song titled "Après Moi" (notice the UTF-8 character), the client would fail with the message:

```
Error: A problem occurred communication with the server. ...
```

ie, the server returned a 500.

Then looking in the `subsonic.log` the error message in the title of this git issue was logged.

I noticed this issue didn't occur when running supysonic as [stand alone](https://github.com/spl0k/supysonic/blob/541efa6437c1f43eeea146f0acb44b0e04bda50e/README.md#as-a-standalone-debug-server), only from my Apache2 WSGI endpoint.

Similar to what's mentioned in the README.md, for me it was solved by adding:

```
export LANG="en_US.utf8"
export LC_ALL="en_US.UTF-8"
```

before the `export LANG` line in my `/etc/apache2/envvars` file and issuing a `sudo service apache2 restart`.

**Comment by baldurmen** [comment]
@spl0k I guess since this bug is not really one, this can be closed?

If the issue is that the documentation is not clear enough, I can try and propose a PR.
