### ISSUE TITLE
Genres Support

### ISSUE THREAD

**Issue by c64bob** [spl0k/supysonic#47]
Any chance of bumping the API to v1.9 and supporting genres?

**Comment by spl0k** [comment]
Hello.
I might consider it. Any specific feature you would like to see in particular?

**Comment by c64bob** [comment]
I'd love to be able to browse by genre, or have my player create a random playlist for a genre.
Thanks

**Comment by sprnza** [comment]
Any update on this? I miss this feature too

**Comment by spl0k** [comment]
Hi.
Sorry for the late reply. I'm a bit busy at the moment and don't have much time to work on supysonic, but genres are on my short-list of stuff to be implemented next.

**Comment by spl0k** [comment]
You should now be able to get the list of genres and search songs by genre. Filtering albums by genre isn't supported yet.
I spent a minimal time testing this. I didn't get any error on the few cases I considered, but there's a non-zero probability I missed something.

**Comment by sprnza** [comment]
Yay! Thank you so much!!

**Comment by sprnza** [comment]
Unfortunately Ultrasonic is not able to display list of genres. Postman returns the json correctly though. Could be Ultrasonic specific issue.

**Comment by sprnza** [comment]
Dsub displays the list of genres correctly though.
