### ISSUE TITLE
Duplicate albums if there are multiple artists

### ISSUE THREAD

**Issue by plabadens** [spl0k/supysonic#52]
It seems that supysonic returns multiple album entries when some tracks have different artists. In this case, we get one album per track artist, all with the same name. In this case, it would be nice if supysonic supported the album artist metadata field, in order to group albums by album artists.

**Comment by spl0k** [comment]
Done, please note that a schema upgrade is needed. You'll find migration scripts in the *schema/migration* folder.
You might also want to do an full rescan of the library with the new `--force` option added to the CLI.
