### ISSUE TITLE
Transcoder processes hangs on dropped connection

### ISSUE THREAD

**Issue by ypopovych** [spl0k/supysonic#55]
Hi.
First of all - thanks! Great software!

I found only one big problem up to this moment:
When stream fails (connection closed by the client) server shows exception, but transcoder is working. So it hangs (because output stream already closed).

Maybe we can add some exception handler for closed stream and send SIGTERM to the transcoder, or even redirect it's output to /dev/null (if it can't be closed by SIGTERM)

**Comment by ypopovych** [comment]
Still hangs :(
Seems as it can't be terminated until it writes all bytes in cache.

Hangs on flac + lame transcoding (flac to mp3)

**Comment by spl0k** [comment]
Hi.
Could you please post your transcoding configuration?

**Comment by ypopovych** [comment]
`
transcoder_mp3_mp3 = lame --quiet --mp3input -b %outrate %srcpath -
transcoder = ffmpeg -i %srcpath -ab %outratek -v 0 -strict -2 -f %outfmt -
decoder_mp3 = mpg123 --quiet -w - %srcpath
decoder_ogg = oggdec -o %srcpath
decoder_flac = flac -d -c -s %srcpath
encoder_mp4 = ffmpeg -i pipe:0 -b:a #outratek -v 0 -strict -2 -f adts -
encoder_mp3 = lame --quiet -b %outrate - -
encoder_ogg = oggenc -q -M %outrate -
`

It's using decoder_flac -> encoder_mp3

**Comment by dpraul** [comment]
I believe I'm experiencing this issue as well, although I haven't narrowed it down. I have now twice had the application become unresponsive while I'm out-and-about. Here's the screen output from the last time it happened (cleaned of sensitive info):

```
[pid: 21452|app: 0|req: 43/43] {{IP}} () {32 vars in 706 bytes} [Fri Nov 17 14:37:12 2017] GET /rest/stream.view?u={{USER}}&p={{PASS}}&v=1.2.0&c=DSub&id=894a92f7-d6ac-409d-b230-7ea0d3a99198&maxBitRate=320 => generated 18869777 bytes in 1248 msecs (HTTP/1.1 200) 2 headers in 79 bytes (2305 switches on core 0)
[pid: 21452|app: 0|req: 44/44] {{IP}} () {32 vars in 706 bytes} [Fri Nov 17 14:37:14 2017] GET /rest/stream.view?u={{USER}}&p={{PASS}}&v=1.2.0&c=DSub&id=02df1817-0325-4e68-a3ce-53cc3ce79752&maxBitRate=320 => generated 20528046 bytes in 1399 msecs (HTTP/1.1 200) 2 headers in 79 bytes (2507 switches on core 0)
[pid: 21452|app: 0|req: 45/45] {{IP}} () {32 vars in 706 bytes} [Fri Nov 17 14:37:18 2017] GET /rest/stream.view?u={{USER}}&p={{PASS}}&v=1.2.0&c=DSub&id=39ad17ef-7dbe-4c7d-99c0-c6d29f0a43d4&maxBitRate=320 => generated 19937928 bytes in 1662 msecs (HTTP/1.1 200) 2 headers in 79 bytes (2437 switches on core 0)
[pid: 21452|app: 0|req: 46/46] {{IP}} () {32 vars in 680 bytes} [Fri Nov 17 14:37:33 2017] GET /rest/getAlbum.view?u={{USER}}&p={{PASS}}&v=1.2.0&c=DSub&id=d7c83d6f-0dca-4269-b744-44c9e7a7825d => generated 3948 bytes in 24 msecs (HTTP/1.1 200) 3 headers in 97 bytes (1 switches on core 0)
uwsgi_response_write_body_do() TIMEOUT !!!
IOError: write error
```
