### ISSUE TITLE
Supysonic fails to start

### ISSUE THREAD

**Issue by illumilore** [spl0k/supysonic#60]
When launching, it fails to start with error:
$ python cgi-bin/server.py 
Traceback (most recent call last):
  File "cgi-bin/server.py", line 22, in <module>
    from supysonic.web import create_application
ImportError: No module named supysonic.web

**Comment by nwokeo** [comment]
You may need to add the supysonic directory to your PYTHON_PATH.

Something like:
`export PYTHONPATH="${PYTHONPATH}:/var/supysonic/supysonic"`

**Comment by baldurmen** [comment]
@nwokeo Could you please be more specific? I had the same error, but adding the directory to my python path did fix it for me running supysonic manually.

I can't run it with Apache WSGI though. Adding `WSGI PythonPath /var/www/supysonic/supysonic` does not seem to help either...

**Comment by spl0k** [comment]
As mentioned by @nwokeo you can add supysonic to the python path.
Another solution would be to install supysonic, either globally or in a virtual environment by running the following command:
```
python setup.py install
```

Using a virtualenv or setting a python path for Apache WSGI require some configuration directives.
You can easily find some examples, such as
https://stackoverflow.com/a/26518501
https://stackoverflow.com/a/39949355

**Comment by baldurmen** [comment]
I think this can be closed.

**Comment by spl0k** [comment]
Closing, as @illumilore didn't give any follow-up.
