### ISSUE TITLE
Transcoding flac to mp3 does not change file extension

### ISSUE THREAD

**Issue by baldurmen** [spl0k/supysonic#62]
Transcoding `flac` to `mp3` does not change the file extension. I'm downloading the files with DSub and even though they are transcoded fine and end up being `mp3` files, they are still named `*.flac`:

    $ file "01-Pints of Guinness Make You Strong.complete.flac"
    > 01-Pints of Guinness Make You Strong.complete.flac: MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo

I'm using the recommended transcoding options on the wiki:

```
transcoder_mp3_mp3 = lame --quiet --mp3input -b %outrate %srcpath -
transcoder = ffmpeg -i %srcpath -ab %outratek -v 0 -f %outfmt -
decoder_mp3 = mpg123 --quiet -w - %srcpath
decoder_ogg = oggdec -o %srcpath
decoder_flac = flac -d -c -s %srcpath
encoder_mp3 = lame --quiet -b %outrate - -
encoder_ogg = oggenc2 -q -M %outrate -
```

This is not a critical bug since most players won't care and will play the files anyway, but I wondered for a while why the transcoding was not working even though I could see `flac` and `lame` running on the server.

**Comment by spl0k** [comment]
Supysonic doesn't send any filename when transcoding. How did you download this file exactly? Did you enable transcoding from DSub of from the web interface?
I think it could be caused by the missing `transcodedContentType` and `transcodedSuffix` from the search/browse API responses but I'm not so sure. I'll run some tests...

**Comment by baldurmen** [comment]
I downloaded the file using regular DSub caching. Files are saved in `Android/media/github.daneren2005.dsub/music`.

I simply transferred that file to my computer and ran `file` on it.
