### ISSUE TITLE
About #65

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#66]
@spl0k Do you like the PR #65?

I'm thinking to touch to all message flashing to add categories and have different colors that depends of importance of message, but I don't know if you like the changes.

Greetings.

**Comment by spl0k** [comment]
I didn't have the time to look in details, but it seems great 👍
I have concerns with 97fb5232e5f08a790751934fbe358586544e96cf though, so expect a review (might come in 2 weeks, I'm on holidays)

**Comment by ogarcia** [comment]
Ok. No problem, I make several tests to 97fb523 but four eyes sees more than two.

I will try implement some unit tests in other branch in the meantime of your holidays 😉
