### ISSUE TITLE
Problem with passwords

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#67]
I'm working on the unit tests and discover a bug caused by `__decode_password` in [user manager][1]. I think that is old code that can be deleted without problem, but at this moment cause one issue that is what your password cannot start with `enc:`.

The second bug is that you cannot use non ascii characters in passwords. This is caused by the construction `hashlib.sha1(salt + password).hexdigest()` in [the return][2]. The problem is that the password is unicode but salt not and yu gives an UnicodeEncodeError like this.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "supysonic/managers/user.py", line 153, in __encrypt_password
    return hashlib.sha1(salt + password).hexdigest(), salt
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 6: ordinal not in range(128)
```

The safest method that I foud to fix this is change the return to manage password and salt as utf8:
```python
return hashlib.sha1(salt.encode('utf-8') + password.encode('utf-8')).hexdigest(), salt
```

[1]: https://github.com/spl0k/supysonic/blob/master/supysonic/managers/user.py#L155
[2]: https://github.com/spl0k/supysonic/blob/master/supysonic/managers/user.py#L152

**Comment by ogarcia** [comment]
After several tests the problem is that `hashlib.sha1` need a str without unicode codes. When you pass a string without unicode characters the conversion can be made _automagically_ using default ascii encoding, but if the string have extended characters then the code can't handle it.

The solution is encode both strings as str as I say before.

```python
return hashlib.sha1(salt.encode('utf-8') + password.encode('utf-8')).hexdigest(), salt
```

**Comment by ogarcia** [comment]
Hi @spl0k, I have some small questions / proposals that I wanted to know your opinion.

I fix this issue and made some changes in several files to make project more clean with circular dependencies, but before send you a PR tell me wat do you think about the following.

- I made the headers of touched files more simple. You can see the result [here][1]. I think that is more clean and the given information is the same (part of supysonic, copyright and license).
- In the files where I made several changes in code I add me in copyright line (Sample [here][2] and [here][3]). This is simply credit my changes.
- The files that I toched are re-tabbed. I think that is better use four spaces that one tab.
- In these files I made some _visual_ changes as make imports one for module or add more blank lines and return carriages. This is for complying with the style PEP.

No more, you'll tell me what you think.

[1]: https://github.com/ogarcia/supysonic/blob/98873a4394289022c3c6833f8b6b69d974cd33d4/supysonic/managers/user.py
[2]: https://github.com/ogarcia/supysonic/blob/clean/supysonic/templates/addfolder.html
[3]: https://github.com/ogarcia/supysonic/blob/clean/supysonic/web.py

**Comment by spl0k** [comment]
About `UserManager.__decode_password`, this is not old code and is used by pre-1.13.0 clients/servers. See the [Subsonic API](http://www.subsonic.org/pages/api.jsp) introduction about query parameters.
But you're right that it prevents having passwords starting with `enc:`. Actually that method shouldn't be here or called from any other `UserManager` method. That code should actually be executed when passwords are retrieved from query parameters ([1], [2], [3]).

[1]: https://github.com/spl0k/supysonic/blob/2b3155ceb80e4297574567f501799d026a4fb024/supysonic/api/__init__.py#L67
[2]: https://github.com/spl0k/supysonic/blob/2b3155ceb80e4297574567f501799d026a4fb024/supysonic/api/user.py#L53
[3]: https://github.com/spl0k/supysonic/blob/2b3155ceb80e4297574567f501799d026a4fb024/supysonic/api/user.py#L82

For headers I actually followed the advice given by the license, but it's true it can be shortened. Your version, with added credit, suits me fine.

**Comment by ogarcia** [comment]
Ok. In this case I think that we can use this method in `__decode_password`

```python
def __decode_password(password):
    if not password.startswith('enc:'):
        return password

    try:
        return binascii.unhexlify(password[4:])
    except:
        return password
```

With this piece of code, a password that starts with `enc:` have no problem.

Ok. I'll make the changes :wink:
