### ISSUE TITLE
Improve cover art support

### ISSUE THREAD

**Issue by spl0k** [spl0k/supysonic#81]
- [x] other image formats
- [x] possible other filenames
- [ ] embedded in media files

**Comment by davebiffuk** [comment]
Hi, for historical reasons my mp3 collection has "AlbumArt.jpg" files not "cover.jpg". I made a change to support either filename which is here: https://github.com/davebiffuk/supysonic/tree/coverart_in_albumartjpg Is that of interest? Is there value in making the filename configurable and/or a list? Thanks!

**Comment by spl0k** [comment]
Hi. I haven't put much thought on it yet, but I think I'll build something that take any image in the same folder of a media file (to get away from that naming constraint). If there are several image files they'll be sorted using some scoring system and the one with the highest score will be used.

There's nothing on your branch btw.

**Comment by davebiffuk** [comment]
Huh, not sure what happened with the branch, sorry - the change is there now.

"Any image file" is an interesting thought. In my collection I found various possibilities: AlbumArt.jpg, back_cover.jpg, back.jpg, cd1.jpg, cover.jpg, front.jpg, listing.jpg. It probably makes sense to score "*back*" low.

**Comment by potatoru** [comment]
Hello! Thanks for your work.

Embedded artworks support is highly necessary. Could you please add it?

**Comment by spl0k** [comment]
It's in the plans. I can't tell you when this is going to be implemented though.
