### ISSUE TITLE
Web UI logs out

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#90]
While I navigate on the web UI I constantly being knoked out to login page. I'm even not able to add a user using UI.
Nothing is being spitted out in the httpd log.

**Comment by spl0k** [comment]
Are you running _supysonic_ behind a reverse proxy or as a WSGI app?

**Comment by sprnza** [comment]
WSGI App with Apache

On March 20, 2018 8:55:06 PM GMT+03:00, Alban <notifications@github.com> wrote:
>Are you running _supysonic_ behind a reverse proxy or as a WSGI app?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spl0k/supysonic/issues/90#issuecomment-374695816

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by spl0k** [comment]
Do you have something in Apache's configuration that would affect how requests are dispatched across processes? Either at WSGI level or on the whole Apache.

I suspect an issue with the cookies' secret key, which is randomly generated when the application starts.

**Comment by sprnza** [comment]
Nothing special here is the [conf file](http://share.speran.info/9qgm0p2k.conf)

**Comment by spl0k** [comment]
Could you please checkout the _issue90_ branch and tell me if the problem still occurs?

**Comment by sprnza** [comment]
To be clear what I'm doing:
```
git checkout -b issue90
systemctl restart httpd
```
And when I'm trying to create a new user the problem still occurs-  I'm beeng kicked off to login page when I click "Submit" on the "Add user" page.
I use luakit, that uses webkit2gtk.

**Comment by spl0k** [comment]
`git checkout -b` create a new branch pointing to the current `HEAD`. So you're most likely on the same commit than `master`.
To have the branch tracking and synced with the one with the same name on the remote repository use the following commands (assuming you're currently on `issue90`)

    git fetch
    git branch -u origin/issue90
    git merge origin/issue90

**Comment by sprnza** [comment]
Yes I was missing that . It still kicks out with the branch merged. Also tested on Palemoon 27.8

**Comment by sprnza** [comment]
I've migrated to docker and I don't have the issue anymore. As soon as it seems to me that I had an extremely broken set up I close this one too.
