### ISSUE TITLE
UserWarning:  The psycopg2 wheel package will be renamed.

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#91]
I'm sure you already know that all cli tools return this warning.
```
/usr/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
```
Is there any action from user side required? I've tried to install psycopg2-binary, so should I just wait for supysonic adopt the new module's name?

**Comment by spl0k** [comment]
You just have to uninstall `psycopg2` and install `psycopg2-binary` and that should remove this warning.
Documentation have been updated.

**Comment by sprnza** [comment]
Doesn't work like that. Get this error:
```
    from psycopg2cffi import compat                                    
ModuleNotFoundError: No module named 'psycopg2cffi' 
```

**Comment by sprnza** [comment]
Yep, sorry.
