### ISSUE TITLE
Scan audio files even when they have only some/no tags

### ISSUE THREAD

**Issue by hhm0** [spl0k/supysonic#94]
At present, files within the scanned directories are not added if they are missing some tags (e.g. `artist`) or have no tags whatsoever.

It would be awesome if these could be included, even if that means that they wouldn't show up in the `id3` methods, since they can still show up in the non-`id3` methods.

The filename can be used as a title (where the `title` tag is not present), since every file will have a filename.

Thanks for the wonderful project!

**Comment by spl0k** [comment]
The scanner should now accept files without metadata or with missing tags.
Missing tags default to:
- track title: filename
- artist: "_[unknown]_"
- album: "_[non-album tracks]_"

Setting default values was easier than allowing null values (no database schema change) and allow the files to be accessible whatever browsing method you use.

**Comment by hhm0** [comment]
Thanks so much for implementing this! :-)
